###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}

### new note with token
POST http://localhost:3001/api/notes/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3R0IiwiaWQiOiI2NGQzNmRhODI1YThhZWE0NzI0YmM4NTkiLCJpYXQiOjE2OTE1ODE2MDV9.52oNAC87vEzp1t8d8kKIuKRp9LPx1TslAuxhDV-PqFw

{
    "content": "is this working",
    "important": true
}